Feature/species registration
qrsnake/qr-snake-front pull request #1
Opened 2021-10-16 06:29 UTC by thayanebatista

### O que foi feito? 
  - [x] alterado icon e nome em index.html
  - [x] adicionada rota para cadastrar especie
  - [x] dividido procurarAnimal.vue em um filho infoAnimal.vue para facilitar e deixar mais bonitão
  - [x] adicionado botão de 'pesquisar' e função para mostrar detalhes do que foi pesquisado quando clicado 
  - [x] adicionei um icon de cobra a pag de login pra ter uma noção ao menos de como ficará quando for uma logo real 
  - [x] adicionado botão de voltar caso o usuario nao queira mais cadastrar um animal 
  - [x] mantive a barra de navegação, ainda não sei como meter um login e pular essa parte pra trabalhar só na tela inicial...
  - [x] extra: adicionei alguns diretorios e alguns arquivos js que é possivel que sejam usados mais tarde para linkar com a api. não tenho certeza se vai ser utilizado ou não pq ainda to aprendendo, mas pra aquietar minha alma ja fiz alguns js... qualquer coisa eu tiro sem problema :)

### Contexto
  > criar a pagina para que seja possível cadastrar um novo animal no banco de dados, com base no que foi feito pelo Fabio na pagina de pesquisa. 

ps.: Ainda tenho algumas duvidas sobre o design e etc.. mas serão tiradas assim que possível.

2021-10-18 23:09 UTC, albertobazilio98 commented on public/index.html
> +    <link rel="icon" href="<%= BASE_URL %>favicon2.ico">
muda o nome pra favicon mesmo

2021-10-18 23:09 UTC, albertobazilio98 commented on src/router/index.js
> +      component: () => import('@/views/CadastrarAnimal.vue'),
usa o import igual dos outros

2021-10-19 15:16 UTC, Farezii commented on src/store/modules/user.js
> +    },
Esse usuario eh soh para testes na pagina de login? Nao podemo esquecer de tirar essas informacoes depois se ele for somente para testes da front-end enquanto nao estiver conectada a backend.

2021-10-19 15:26 UTC, Farezii commented on src/views/ProcuraAnimal.vue
> +      this.$router.push('search/registration');
Por motivos de simplicidade e consistencia, nao seria melhor trocar o nome deste metodo de "registrar" para "cadastrar", para ficar em linha com o botao?

2021-10-19 15:35 UTC, Farezii requested changes
Otimo trabalho, apenas algumas mudancas foram pedidas por ambos os reviewers, segundo os comentarios deixados nos codigos (podem ser vistos sob Conversations):

1. public/index.js : Mudar o nome do icone novo para favicon, para ficar em linha com o resto do codigo;

2. src/router/index.js : modificar o import para ficar igual aos outros imports. Caso tenha uma razao que eh preferivel utilizar este metodo, por favor argumente na conversa desta mudanca;

3. src/store/modules/user.js: Tomar cuidado com este usuario master para que ele nao chegue na versao final, isto pode virar um problema de seguranca;

4. src/views/ProcuraAnimal.vue: modificar nome do metodo "registrar".

Qualquer argumentacao, por favor entrar em contato.

2021-10-20 15:14 UTC, Farezii approved these changes

2021-10-21 21:44 UTC, merged